# Generated by Django 5.1.4 on 2024-12-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='todoapp.todo')),
            ],
        ),
    ]
